### ISSUE TITLE
explanation for the rock-paper-scissors game is slightly off

### ISSUE THREAD

**Issue by cdepillabout** [sharkdp/rock-paper-scissors#1]
I think the explanation for the Rock-Paper-Scissors game is slightly wrong.

On https://shark.fish/rock-paper-scissors/, the explanation is as follows:

> Write three regexes R, P and S such that they match each other in a cyclic Rock, Paper, Scissors fashion. In particular, R matches S, S matches P and P matches R, but R doesn't match S, P doesn't match R and P doesn't match S. 

The last phrase is incorrect:

> but R doesn't match S, P doesn't match R and P doesn't match S

Here's the explanation from code golf:

> Write three regexes R, P and S such that they match each other in a cyclic Rock, Paper, Scissors fashion. In particular, R matches S, S matches P and P matches R, but R doesn't match P, S doesn't match R and P doesn't match S.

I think this is the correct last phrase:

> but R doesn't match P, S doesn't match R and P doesn't match S

**Comment by sharkdp** [comment]
Fixed, thank you very much!
